const dividir= require("./dividir");
const multiplicar= require("./multiplicar");
const sumar= require("./sumar");
const restar= require("./restar");
console.log(sumar(15,5));
console.log(restar(15,5));
console.log(multiplicar(15,5));
console.log(multiplicar(15,0));
console.log(dividir(15,5));
console.log(dividir(15,0));